# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62730a73f3a6a26a7e565ab4a6467ca12d274ecac79ec3b301f28d3c3c06e09a505f0465d9da70adabead6373b82ebd76bff0c63017b44daea544b5d90d735ad

test:
  secret_key_base: 0f27de38254f02a1fc3da942947e5399dce531a670dc1bd2e81f6b622b45ebdbae6afe81ee5d4f1587af26ee6402c156b35946cab961377b98a7c63b0746a753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
